<a href="https://colab.research.google.com/github/mian-adoan98/MachineLearningTutorial/blob/main/PyTorch_Tutorial_2_Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# Tensor Operations

In [6]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
my_torch = my_torch.view(float)
my_torch

tensor([[ 0.0000e+00, 4.9407e-324, 9.8813e-324, 1.4822e-323, 1.9763e-323],
        [2.4703e-323, 2.9644e-323, 3.4585e-323, 3.9525e-323, 4.4466e-323]],
       dtype=torch.float64)

In [7]:
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [24]:
# Inverse matrix using reshape(-1,1)
my_torch2 = my_torch2.reshape(-1,1)
my_torch2

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14]])

In [25]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Using view
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
# Difference : Reshape and View
# https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [29]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
my_torch5[1] = 4145
my_torch5[5] = 1254
my_torch5

tensor([   0, 4145,    2,    3,    4, 1254,    6,    7,    8,    9])

In [42]:
# Slices
my_torch7 = torch.arange(15)
my_torch7

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
# Grab a specific item
my_torch7[4]

tensor(4)

In [44]:
# Grab a slice
my_torch7[2:5]

tensor([2, 3, 4])

In [46]:
my_torch8 = my_torch7.reshape(5,3)
my_torch8

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [55]:
# return column
k1 = my_torch8[:, 1]
k2 = my_torch8[:, 2]
k2
# diff_k = k2 -k1
# diff_k

tensor([ 2,  5,  8, 11, 14])

In [63]:
k1 = my_torch8[:, 1:2]
k1

tensor([[ 1],
        [ 4],
        [ 7],
        [10],
        [13]])

In [56]:
# return row
r1 = my_torch8[0,:]
r2 = my_torch8[2,:]
r2

tensor([6, 7, 8])

In [ ]:
a