<a href="https://colab.research.google.com/github/mian-adoan98/MachineLearningTutorial/blob/main/PyTorch_Tutorial_3_Tensor_Math_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATIONS**
+ Add, Subtract, Multiply, Divide, Remainders, Exponents
+ Shorthand, Longhand
+ Reassignment

In [7]:
import torch
import numpy as np

In [39]:
tensorA = torch.tensor([1,2,3,4])
tensorB = torch.tensor([5,6,7,8])

In [14]:
# Addition
tensorA + tensorB # adding shorthand
torch.add(tensorA, tensorB) # adding longhand

tensor([ 6,  8, 10, 12])

In [15]:
# Sutraction
tensorA - tensorB
torch.sub(tensorA, tensorB)

tensor([-4, -4, -4, -4])

In [17]:
# Multiplication 1: component-wise
tensorA*tensorB
torch.multiply(tensorA, tensorB)
torch.mul(tensorA, tensorB)

tensor([ 5, 12, 21, 32])

In [20]:
# Division 1: Component-wise
tensorB/tensorA # tensor([5.0000, 3.0000, 2.3333, 2.0000])
tensorB//tensorA # tensor([5, 3, 2, 2])

torch.div(tensorB, tensorA) # tensor([5.0000, 3.0000, 2.3333, 2.0000])

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [21]:
# Remainder
tensorB % tensorA

tensor([0, 0, 1, 0])

In [22]:
torch.remainder(tensorB, tensorA)

tensor([0, 0, 1, 0])

In [26]:
# Exponents: component-wise
tensor_kw = torch.tensor([2,2,2,2])
torch.pow(tensorA,tensor_kw)

tensor([ 1,  4,  9, 16])

In [29]:
# another way to write longhand
tensorA.add(tensorB) # same for mul, div, pow, etc.

tensor([ 6,  8, 10, 12])

In [40]:
# Reassignment
tensorA

tensor([1, 2, 3, 4])

In [41]:
tensorA = tensorA + tensorB # tensor([ 6,  8, 10, 12])
tensorA

tensor([ 6,  8, 10, 12])

In [ ]:
tensorA.add_(tensorB) # tensor([ 6,  8, 10, 12])